name: hardhat-integration-test
on: [push]

jobs:
  integration-test:
   runs-on: ubuntu-latest
   name: Solidity integration test continuous integration
   steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Environment Setup
      uses: actions/setup-node@v3
      with:
        node-version: 18.15.0

    - name: Integration test
      uses: ambersun1234/hardhat-test@v1
      with:
       network: sepolia
       private_key: ${{ secrets.PRIVATE_KEY }}
       rpc_url: ${{ secrets.RPC_URL }}